SERIAL_PORT = "COM4"
SERIAL_BAUDRATE = 9600

DEVICE_NAME = "optical_amp_1"

INFLUX_ENABLED = True

INFLUX_URL = "http://localhost:8086"
INFLUX_TOKEN = "RAEkYikFlc8ZB-z9XxePKofc3Wd4EbYb9zJV6znfgzaLaOWudvadOEGjm4tGkDR_0MaBNvQpGltq0SBsECCRJA=="
INFLUX_ORG = "agh"
INFLUX_BUCKET = "sensors"

MEASUREMENT_NAME = "optical_amp_status"
SETPOINT_MEASUREMENT_NAME = "optical_amp_setpoint"

HISTORY_MEMORY_LIMIT = 10000

PERSISTED_STATE_FILE = "persisted_state.json"

SYSLOG_ENABLED = True
SYSLOG_HOST = "127.0.0.1"
SYSLOG_PORT = 514
SYSLOG_APP_NAME = "amp-dashboard"
SYSLOG_FACILITY = 16
